POST    http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvaXJhIiwiaWQiOiI1ZjJkMTMxMzE2NDY2ZDI0ZGNhYWNhODMiLCJpYXQiOjE1OTY3OTQzNDh9.Z55fsFtUxnI6Ry2ftu5o-Mf0b5AVd_GuYIdNaOTgUVI
  
  {
    "title": "Rain forest",
   "author": "Monkey King",
   "url" :"www.forest.my"

}

